name: Trading Bot

on:
  schedule:
    - cron: '*/20 * * * *' # يعمل كل 20 دقيقة
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run Bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python bot.py
